name: ProjectiCad_$(Date:yyyyMMdd)$(R:.r)

trigger:
- main

pool:
  name: Default

variables:
  azureSubscription: 'd439147f-ff34-4075-98ad-c0c9d864d6c1'
  ResourceGrpName: 'RG-GroupMosiba'
  wepAppPlan: 'Appplan-Mosiba'
  webAppName: 'Mosiba'
  environmentName: 'Dev'

stages:
- stage: Build_and_Test
  displayName: BUILD_CODE
  jobs:
  - job:
    displayName: Building_App
  pool:
   name: Default
   steps:
    - task: NodeTaskRunnerInstaller@0
      inputs:
        nodeVersion: '10'
    - task: Npm@1
      inputs:
        command: 'install'
        workingDir: '''$(System.DefaultWorkingDirectory)'''

    - task: Npm@1
      inputs:
        command: 'build'
        workingDir: '$(System.DefaultWorkingDirectory)'

    - task: Npm@1
      inputs:
        command: 'publish'
        workingDir: '''$(System.DefaultWorkingDirectory)'''

- stage: DEPLOY_STAGE
  dependsOn: Build_and_Test
  displayName: DEPLOYING_TO_DEV
  jobs:
  - deployment: 
    displayName: Deploying Mosiba
  pool:
   name: Default  
   steps:
    - task: AzureWebApp@1
      inputs:
        azureSubscription: 'Outlook Zone(962b4151-437e-49ed-8400-d11abfcc3073)'
        appType: 'webAppLinux'
        appName: 'Mosiba'
        package: '$(System.DefaultWorkingDirectory)/**/*.zip'
        runtimeStack: 'NODE|24-lts'
        startUpCommand: 'npm run start'
    





